import {Document, Schema, model} from 'mongoose';
import { TweetType } from '../types/tweet.type';

const tweetSchema: Schema = new Schema({
  // Q: App does not run when this is uncommented. Why?
  // Reasearched and found i should not include _id here as it is auto generated by compass
  // _id: {
  //   type: String, 
  //   required: true
  // },
  tweetName: { 
    type: String, 
    required: true,
    index: true,
  },
  userId: {
    type: Schema.Types.ObjectId,
    required: true,
    ref: 'UserModel',
  },
  text: {
    type: String,
    required: true,
    maxlength: 200,
  },
  media: {
    type: String,
  },
  likes: {
    type: Number, 
    min: 0,
    default: 0,
  },
  createdAt: {
    type: Date, 
    default: Date.now,
  }
},{collection: 'tweets'});

//Q: What is the purpose of the & Document? 
export const TweetModel = model<TweetType & Document>('TweetModel', tweetSchema);